### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by rahulc07** [rahulc07/tucana-studio#1]
- [ ] Neptune Completion with Config Support
- [ ] Base HTML/UI
   - [ ] Displaying Thumbnails
   - [ ] Sharing Panel
       - [ ] Filtering and Searching  
       - [ ] Commenting
       - [ ] Auto moderation
   - [ ] Desktop Customization
        -  [ ] Gnome
        -  [ ] KDE
        -  [ ] XFCE
        -  [ ] Cinnamon
    - [ ] Dashboard
- [ ] Backend
    - [ ] Decide on a DB strategy 
    - [ ] Sharing Support
       - [ ] Login & Signup via Authentik
       - [ ] Comments
       - [ ] Validation
    - [ ] SquashFS creation and curation
    - [ ] ISO Creation
    - [ ] Packaging Oddities
    - [ ] User Customization Support
       - [ ] Autostart
       - [ ] Github Dots Import
       - [ ] Desktop Wallpapers
       - [ ] Modifying Desktop
          - [ ] Gnome
          - [ ] KDE
          - [ ] XFCE
          - [ ] Cinnamon 

If anything is off or needs to be decided about any of these things a new issue will be opened
